---
- hosts: rpis

  vars:
    WWW_PATH: "/var/www/html/rpi"

  tasks:

  - name: Create a directory if it does not exist
    file:
      path: "{{ WWW_PATH }}"
      state: directory
      mode: 0655
    become: yes
  - name: Publishes janus.js in Nginx public directory
    copy:
      src: janus.js
      dest: "{{ WWW_PATH }}/janus.js"
      mode: 0655
    become: yes
  - name: Publishes main.js in Nginx public directory
    copy:
      src: main.js
      dest: "{{ WWW_PATH }}/main.js"
      mode: 0655
    become: yes
  - name: Publishes index.html in Nginx public directory
    copy:
      src: index.html
      dest: "{{ WWW_PATH }}/index.html"
      mode: 0655
    become: yes