---
- hosts: rpis

  tasks:

  - name: Install libgstreamer (Gstreamer)
    apt:
      name: libgstreamer1.0-0
    become: yes

  - name: Install gstreamer1.0-plugins-base (Gstreamer)
    apt:
      name: gstreamer1.0-plugins-base
    become: yes

  - name: Install gstreamer1.0-plugins-good (Gstreamer)
    apt:
      name: gstreamer1.0-plugins-good
    become: yes

  - name: Install gstreamer1.0-plugins-bad (Gstreamer)
    apt:
      name: gstreamer1.0-plugins-bad
    become: yes

  - name: Install gstreamer1.0-plugins-ugly (Gstreamer)
    apt:
      name: gstreamer1.0-plugins-ugly
    become: yes

  - name: Install gstreamer1.0-libav (Gstreamer)
    apt:
      name: gstreamer1.0-libav
    become: yes

  - name: Install gstreamer1.0-doc (Gstreamer)
    apt:
      name: gstreamer1.0-doc
    become: yes

  - name: Install gstreamer1.0-tools (Gstreamer)
    apt:
      name: gstreamer1.0-tools
    become: yes

  - name: Copies raspivid execution script
    copy:
      src: raspivid.sh
      dest: /home/pi/raspivid.sh
      mode: 0755

  - name: Copies janus execution script
    copy:
      src: janus.sh
      dest: /home/pi/janus.sh
      mode: 0755
